name: Ruby Gem

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Publish to RubyGems1
      if: ${{ github.event.base_ref == 'refs/heads/master' }}
      run: |
        echo ${GITHUB_REF}
        gem build barthologem.gemspec
        RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        gem push barthologem-${RELEASE_VERSION}.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}

    - name: Publish to RubyGems2
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo ${GITHUB_REF}
        gem build barthologem.gemspec
        RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        gem push barthologem-${RELEASE_VERSION}.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}

    - name: Testme
      run: |
        echo $github.ref
