name: Ruby Gem

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        version: 2.6.x

    - name: Publish to RubyGems
      run: |
        gem --version
        gem build barthologem.gemspec
        RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        mkdir ~/.gem
        touch ~/.gem/credentials
        gem push barthologem-${RELEASE_VERSION}.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}

    - name: Environment
      run: |
        echo "pwd: $(pwd)"
        echo "\$HOME: $HOME"
        env
        sudo apt-get install -y tree
        tree
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: Testme
      run: |
        echo $github.ref
